[package]
name = "xck"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#RustCrypto/traits/
aead = "0.5.2"

#RustCrypto/AEADs/
chacha20poly1305 = "0.10.1"