[package]
name = "xck"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#rust-random

#/rand/
rand = "0.8.5"

#/rand/rand_core/
rand_core="0.5.0"

#/rand/rand_chacha/
rand_chacha = "0.3.1"


#Rust Crypto

#/traits
aead = {version="0.5.2", default-features = false}

#/utils/
zeroize = "1.3.0"

#/stream-ciphers/
chacha20 = "0.9.1"

#/universal-hashes/
poly1305 = "0.8.0"




[features]
default = ["alloc"]

alloc = ["aead/alloc"]

std = ["aead/std", "alloc"]