[package]
name = "xck"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#rust-random/rand/
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_core="0.5.0"


#RustCrypto/traits/
aead = "0.5.2"

#RustCrypto/AEADs/
chacha20poly1305 = "0.10.1"