[package]
name = "xck"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#rust-random/rand/
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_core="0.5.0"


#RustCrypto/traits/
aead = "0.5.2"

#RustCrypto/AEADs/
chacha20poly1305 = "0.10.1"

#BLAKE3-team/BLAKE3/
blake3 = "1.3.3"

#RustCrypto/hashes/
sha2 = "0.10.6"

#
ed25519-dalek = "1.0.1"

#
#x25519-dalek = {version="2.0.0-rc.2",features=["static_secrets"]}

#RustCrypto/rsa/
#rsa = "0.9.2"

#clap-rs/clap/
clap = {version="4.3.8" ,features=["derive"]}